# Generated by Django 4.1.1 on 2022-10-04 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_ingredient_user_menuitem_ingredients_list_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='additional_ingredients_list',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='ingredients_list',
            field=models.JSONField(default=dict),
        ),
    ]
