# Generated by Django 4.1.1 on 2022-10-05 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_drink_additional_ingredients_list_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='size',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='order',
            name='ingredients_list',
            field=models.JSONField(default=dict),
        ),
        migrations.DeleteModel(
            name='Drink',
        ),
    ]
