# Generated by Django 4.1.1 on 2022-10-10 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_user_authlevel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderStatus',
            field=models.CharField(default='unfullfilled', max_length=200),
        ),
    ]
