# Generated by Django 4.1.1 on 2022-10-10 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_order_orderstatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='ingredients_list',
            new_name='ingredientList',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='time',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='ingredients_list',
            new_name='ingredientList',
        ),
    ]
