# Generated by Django 4.1.1 on 2022-10-24 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0007_rename_ingredients_list_menuitem_ingredientlist_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="User",
            new_name="UserInfo",
        ),
    ]
