# Generated by Django 4.1.1 on 2022-10-30 00:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("base", "0010_alter_order_options_alter_order_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userinfo",
            name="password",
        ),
        migrations.RemoveField(
            model_name="userinfo",
            name="userName",
        ),
        migrations.AddField(
            model_name="userinfo",
            name="user",
            field=models.OneToOneField(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="balance",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="hoursWorked",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
